// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjqotjfdifodujgtmnhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqcW90amZkaWZvZHVqZ3RtbmhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDQyNjgsImV4cCI6MjA1ODQyMDI2OH0.O_RnQkGICWgWGT5y4VwCKy59QUohPohGenulwPi30wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);